comment: false

codecov:
  token: 400f2abb-c55e-4f04-9dc3-9899f2461647

coverage:
  status:
    project:
      default:
        target: auto
        threshold: null #1%
    patch:
      default:
        target: auto
        threshold: null #1%
